import type { Decision, ProofExport } from "./types.ts";

const esc = (s: string): string =>
  s.replace(/[<>&'"]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", "'": "&#39;", '"': "&quot;" })[c] as string);

const DECISION_LABEL: Record<Decision, string> = {
  CLEAR: "No test required",
  MUST_TEST: "Test required",
  AMBIGUOUS: "Could not confirm — advised to call",
  UNREACHABLE: "Line unreachable — advised to call",
};

const DECISION_CLASS: Record<Decision, string> = {
  CLEAR: "d-clear",
  MUST_TEST: "d-test",
  AMBIGUOUS: "d-verify",
  UNREACHABLE: "d-verify",
};

function fmtTime(iso: string): string {
  // Keep it simple and locale-stable: "YYYY-MM-DD HH:MM UTC".
  return `${iso.slice(0, 10)} ${iso.slice(11, 16)} UTC`;
}

/**
 * Render a self-contained, printable HTML compliance record. A lawyer or PO can
 * open it and "Print → Save as PDF". `sample` adds a visible demo banner so a
 * mockup is never mistaken for a genuine record.
 */
export function renderProofHtml(exp: ProofExport, opts: { sample?: boolean } = {}): string {
  const s = exp.summary;
  const rows = exp.entries
    .map(
      (e) => `      <tr>
        <td>${esc(e.day)}</td>
        <td>${esc(e.at.slice(11, 16))} UTC</td>
        <td class="${DECISION_CLASS[e.decision]}">${esc(DECISION_LABEL[e.decision])}</td>
        <td class="heard">${e.heardExcerpt ? esc(e.heardExcerpt) : "<em>—</em>"}</td>
      </tr>`,
    )
    .join("\n");

  const banner = opts.sample
    ? `<div class="sample">SAMPLE — demonstration data, not a genuine record</div>`
    : "";

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Check-in Compliance Record — ${esc(exp.userName)}</title>
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { font: 14px/1.5 -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; color: #1a1a1a; background: #f4f4f5; margin: 0; padding: 32px; }
  .page { max-width: 820px; margin: 0 auto; background: #fff; padding: 40px 44px; border: 1px solid #ddd; }
  .sample { background: #fde68a; border: 1px solid #d9a300; color: #6b4e00; text-align: center; font-weight: 700; letter-spacing: .04em; padding: 8px; border-radius: 6px; margin-bottom: 24px; }
  header { border-bottom: 2px solid #111; padding-bottom: 16px; margin-bottom: 24px; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .sub { color: #555; font-size: 13px; }
  .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 4px 24px; margin: 20px 0; font-size: 13px; }
  .meta div { display: flex; justify-content: space-between; border-bottom: 1px dotted #ddd; padding: 4px 0; }
  .meta .k { color: #666; } .meta .v { font-weight: 600; }
  .cards { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 24px 0; }
  .card { border: 1px solid #e2e2e2; border-radius: 8px; padding: 12px; text-align: center; }
  .card .n { font-size: 26px; font-weight: 700; }
  .card .l { font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: .04em; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 13px; }
  th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #eee; vertical-align: top; }
  th { background: #fafafa; font-size: 11px; text-transform: uppercase; letter-spacing: .04em; color: #555; }
  .heard { color: #444; font-style: italic; }
  .d-clear { color: #15803d; font-weight: 600; }
  .d-test { color: #b91c1c; font-weight: 600; }
  .d-verify { color: #b45309; font-weight: 600; }
  .integrity { margin-top: 28px; padding: 14px 16px; border: 1px solid #cbd5e1; border-radius: 8px; background: #f8fafc; font-size: 12px; }
  .integrity .ok { color: #15803d; font-weight: 700; }
  .integrity code { word-break: break-all; color: #334155; }
  footer { margin-top: 24px; font-size: 11px; color: #777; }
  @media print { body { background: #fff; padding: 0; } .page { border: none; } }
</style></head>
<body><div class="page">
  ${banner}
  <header>
    <h1>Check-in Compliance Record</h1>
    <div class="sub">Generated by ${esc(exp.serviceName)} — an automated daily check-in service used as a backup to the person's own testing-line calls.</div>
  </header>

  <div class="meta">
    <div><span class="k">Name</span><span class="v">${esc(exp.userName)}</span></div>
    <div><span class="k">Participant ID</span><span class="v">${esc(exp.userId)}</span></div>
    <div><span class="k">Period</span><span class="v">${esc(exp.range.from)} → ${esc(exp.range.to)}</span></div>
    <div><span class="k">Generated</span><span class="v">${esc(fmtTime(exp.generatedAt))}</span></div>
  </div>

  <div class="cards">
    <div class="card"><div class="n">${s.checkIns}</div><div class="l">Check-ins</div></div>
    <div class="card"><div class="n">${s.confirmed}</div><div class="l">Confirmed readings</div></div>
    <div class="card"><div class="n">${s.mustTest}</div><div class="l">Test days</div></div>
    <div class="card"><div class="n">${s.verifyYourself}</div><div class="l">Advised to call</div></div>
  </div>

  <table>
    <thead><tr><th>Date</th><th>Time</th><th>Result</th><th>What the line said</th></tr></thead>
    <tbody>
${rows}
    </tbody>
  </table>

  <div class="integrity">
    Integrity: ${exp.integrityVerified ? '<span class="ok">verified ✓</span>' : "<span>NOT verified ✗</span>"} —
    every entry is linked in a tamper-evident hash chain; altering, adding, or reordering any row breaks it.
    <br/>Digest: <code>${esc(exp.digest)}</code>
  </div>

  <footer>
    Results reflect what the automated service heard on the testing line. "Advised to call" means the service could not
    confirm the result with confidence and instructed the participant to call the line themselves. This record is a
    supplement to, not a replacement for, the participant's own obligations.
  </footer>
</div></body></html>`;
}
